BIN2C_LIBS_PPC = -framework Cocoa
BIN2C_PPC = bin2c_ppc.o

all: bin2c
clean: remobj_bin2c

remobj_bin2c:
	-rm -f $(BIN2C_PPC)
	
bin2c: $(BIN2C_PPC)
	g++ -o bin2c -s -L./ $(FLAGS_PPC) $(BIN2C_PPC) $(BIN2C_LIBS_PPC)
	-rm -f $(BIN2C_PPC)
	strip -x -X -S bin2c

bin2c_ppc.o: ../../../src/extralibs/bin2c/bin2c.cpp
	g++ -c -o $(@) $(FLAGS_PPC) ../../../src/extralibs/bin2c/bin2c.cpp
