BIN2C_LIBS_IA64 = -framework Cocoa
BIN2C_IA64 = bin2c_ia64.o
FLAGS_IA64 = -O3 -arch x86_64

all: bin2c
clean: remobj_bin2c

remobj_bin2c:
	-rm -f $(BIN2C_IA64)
	
bin2c: $(BIN2C_IA64)
	g++ -o ../../../release/distrib/replay/bin2c -L./ $(FLAGS_IA64) $(BIN2C_IA64) $(BIN2C_LIBS_IA64)
	-rm -f $(BIN2C_IA64)
	strip -x -X -S ../../../release/distrib/replay/bin2c
	chmod +x ../../../release/distrib/replay/bin2c

bin2c_ia64.o: bin2c.cpp
	g++ -c -o $(@) $(FLAGS_IA64) bin2c.cpp
